[[language]]
name = "dockerfile"
scope = "text.docker"
file-types = ["docker", "podman", "image", "Containerfile", "Dockerfile"]
roots = []

[[language]]
name = "cabal"
scope = "text.cabal"
file-types = ["cabal"]
roots = []

[[language]]
name = "python"
auto-format = true

[[language]]
name = "groovy"
scope = "source.groovy"
injection-regex = "groovy"
file-types = ["groovy", "Jenkinsfile"]
roots = []

[[grammar]]
name = "groovy"
source = { git = "https://github.com/Decodetalkers/tree-sitter-groovy", rev = "gh-pages" }

